const countries = [
  {countryName: 'United_Arab_Emirates' , nameISO3366: 'AE'},
  {countryName: 'Argentina' , nameISO3366: 'AR'},
  // {countryName: 'Austria' , nameISO3366: ' AT'},
  {countryName: 'Australia' , nameISO3366: 'AU'},
  {countryName: 'Belgium' , nameISO3366: 'BE'},
  {countryName: 'Bulgaria' , nameISO3366: 'BG'},
  {countryName: 'Brazil' , nameISO3366: 'BR'},
  {countryName: 'Canada' , nameISO3366: 'CA'},
  {countryName: 'Switzerland' , nameISO3366: 'CH'},
  {countryName: 'China' , nameISO3366: 'CN'},
  {countryName: 'Colombia' , nameISO3366: 'CO'},
  {countryName: 'Cuba' , nameISO3366: 'CU'},
  {countryName: 'Czech Republic' , nameISO3366: 'CZ'},
  {countryName: 'Germany' , nameISO3366: 'DE'},
  {countryName: 'Egypt' , nameISO3366: 'EG'},
  {countryName: 'France' , nameISO3366: 'FR'},
  {countryName: 'United Kingdom' , nameISO3366: 'GB'},
  {countryName: 'Greece' , nameISO3366: 'GR'},
  // {countryName: 'Hong Kong' , nameISO3366: ' HK'},
  {countryName: 'Hungary' , nameISO3366: 'HU'},
  {countryName: 'Indonesia' , nameISO3366: 'ID'},
  {countryName: 'Ireland' , nameISO3366: 'IE'},
  {countryName: 'Israel' , nameISO3366: 'IL'},
  {countryName: 'India' , nameISO3366: 'IN'},
  {countryName: 'Italy' , nameISO3366: 'IT'},
  {countryName: 'Japan' , nameISO3366: 'JP'},
  {countryName: 'South Korea' , nameISO3366: 'KR'},
  {countryName: 'Lithuania' , nameISO3366: 'LT'},
  {countryName: 'Latvia' , nameISO3366: 'LV'},
  {countryName: 'Morocco' , nameISO3366: 'MA'},
  {countryName: 'Mexico' , nameISO3366: 'MX'},
  {countryName: 'Malaysia' , nameISO3366: 'MY'},
  {countryName: 'Nigeria' , nameISO3366: 'NG'},
  {countryName: 'Netherlands' , nameISO3366: 'NL'},
  {countryName: 'Norway' , nameISO3366: ' NO'},
  {countryName: 'New Zealand' , nameISO3366: 'NZ'},
  {countryName: 'Philippines' , nameISO3366: 'PH'},
  {countryName: 'Poland' , nameISO3366: 'PL'},
  {countryName: 'Portugal' , nameISO3366: 'PT'},
  {countryName: 'Romania' , nameISO3366: 'RO'},
  {countryName: 'Serbia' , nameISO3366: 'RS'},
  {countryName: 'Russia' , nameISO3366: 'RU'},
  {countryName: 'Saudi Arabia' , nameISO3366:'SA'},
  {countryName: 'Sweden' , nameISO3366: 'SE'},
  {countryName: 'Singapore' , nameISO3366: 'SG'},
  {countryName: 'Slovenia' , nameISO3366: 'SI'},
  {countryName: 'Slovakia' , nameISO3366: 'SK'},
  {countryName: 'Thailand' , nameISO3366: ' TH'},
  {countryName: 'Turkey' , nameISO3366: 'TR'},
  {countryName: 'Taiwan' , nameISO3366: 'TW'},
  {countryName: 'Ukraine' , nameISO3366: 'UA'},
  {countryName: 'United States' , nameISO3366: 'US'},
  {countryName: 'Venezuela' , nameISO3366: 'VE'},
  {countryName: 'South Africa' , nameISO3366:'ZA'},
];
export default countries;
